// Code generated by tygo. DO NOT EDIT.
/*
  Copyright © 2026 Alexey Shulutkov <github@shulutkov.ru>

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  	http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */
import { type Key, type InterfaceConfig } from "./agent"

//////////
// source: agentsource.go

/**
 * AgentSource is a named, reusable place to fetch the awg-agent binary
 * from when deploying it to a server (see Service.DeployAgent) — shown as
 * a preset in the "Deploy agent" UI instead of typing a URL every time.
 */
export interface AgentSource {
  id: string;
  name: string;
  url?: string;
  /**
   * Path, when set instead of URL, is a path to the agent binary already
   * present on the filesystem of the machine running awg-admin (desktop:
   * the user's own machine; standalone server: that server's host) — read
   * directly and uploaded over SSH the same way a CacheLocally URL preset
   * is, without ever downloading anything. Exactly one of URL or Path is
   * set; CacheLocally is meaningless here (there's nothing to cache) and
   * is always false for a Path-based source.
   */
  path?: string;
  /**
   * CacheLocally, when false (the default), has the *managed server*
   * download URL itself over SSH (curl/wget — see internal/sshclient's
   * DownloadFile) so the binary's bytes never pass through the machine
   * running awg-admin. When true, awg-admin downloads URL once into a
   * local cache (keyed by ID) and uploads it the traditional way on
   * every deploy that uses this source — for servers without outbound
   * internet access to URL, at the cost of awg-admin's own bandwidth.
   */
  cacheLocally?: boolean;
  /**
   * Image, when set instead of URL/Path, is a Docker image reference (e.g.
   * ghcr.io/ks-tool/awg-agent-userspace:latest). Deploying such a source runs
   * the agent as a Docker container on the server (see deploy.ToAgent's docker
   * path) rather than as a systemd unit — for hosts using the userspace
   * amneziawg-go image. Exactly one of URL, Path or Image is set; CacheLocally
   * is meaningless here (Docker pulls the image itself) and is always false.
   */
  image?: string;
  /**
   * Userspace marks a URL/Path source as the *userspace* agent binary
   * (awg-agent-userspace), which runs over systemd with no kernel module. The
   * systemd deploy then skips its AmneziaWG-kernel-module pre-check (which
   * otherwise fails fast, as it must for the kernel agent — see
   * deploy.deploySystemd). Meaningless for an Image source (a Docker image is
   * inherently the userspace agent) — always false there.
   */
  userspace?: boolean;
}

//////////
// source: auth.go

/**
 * AuthCredentials is the single admin account used to log in to the
 * standalone web-server mode (cmd/awg-admin.go). The Wails desktop app
 * never reads this — it already runs as a local single-user process with
 * no network exposure, so it has nothing to authenticate against.
 */
export interface AuthCredentials {
  username: string;
  /**
   * PasswordHash is a bcrypt hash, never the plaintext password.
   */
  passwordHash: string;
  /**
   * BasicAuthEnabled gates the standalone web server behind HTTP Basic
   * Auth (checked against this same Username/PasswordHash) in addition
   * to the existing session-cookie login — off by default. Useful as an
   * extra layer in front of the whole app (including the login page and
   * static assets) when exposing it directly without a reverse proxy.
   */
  basicAuthEnabled?: boolean;
}

//////////
// source: deploystatus.go

/**
 * DeployStatus reports the progress of an in-flight (or just-finished)
 * Service.DeployAgent call for one server, polled by the frontend (see
 * Service.GetDeployStatus) to show step-by-step progress instead of a
 * plain spinner.
 */
export interface DeployStatus {
  /**
   * Step is one of internal/deploy.ToAgent's step-name keys ("connect",
   * "upload_binary", "upload_unit", "upload_env", "upload_tls",
   * "start_service") — deliberately not human-readable text, so the
   * frontend localizes it itself rather than displaying whatever
   * language the backend happens to log in.
   */
  step: string;
  done: boolean;
  /**
   * Error is the deploy's final error message, set only once Done is
   * true and the deploy failed.
   */
  error?: string;
}

//////////
// source: server.go

export interface Server {
  id: string;
  name: string;
  info: ServerInfo;
  ssh: SSHConfig;
  agent: Agent;
  interfaces?: string[];
}
export interface ServerInfo {
  description?: string;
  location?: string;
  tags?: string[];
}
export interface SSHConfig {
  host: string;
  port?: number /* uint16 */;
  user?: string;
  /**
   * Key is a path to the private key file on the machine running awg-admin,
   * not the key body itself. Mutually exclusive with KeyData; KeyData takes
   * precedence when both are set (see internal/sshclient).
   */
  key?: string;
  /**
   * KeyData holds an uploaded private key's raw PEM content, stored
   * directly in the database instead of referencing a path on disk.
   */
  keyData?: string;
  password?: string;
}
export interface Agent {
  addr: string;
  tls?: AgentTLS;
  /**
   * MonitoringDisabled, when true, turns off the agent's CPU/RAM/network/
   * peer metrics collection (see Service.SetServerMonitoring). Zero value
   * (false) keeps monitoring enabled, matching the agent's own default.
   */
  monitoringDisabled?: boolean;
  /**
   * ProfilingEnabled mirrors MonitoringDisabled for the agent's Go runtime
   * profiling (the /debug/pprof endpoints, see Service.SetServerProfiling).
   * Off by default; when true the admin has turned the agent's profiling on
   * and SyncServer re-applies it after a redeploy (the agent starts with
   * profiling off). Surfaced on the dashboard as an icon by the server name.
   */
  profilingEnabled?: boolean;
}
/**
 * AgentStatus is the tri-state health of a server's agent shown on the
 * dashboard (see Service.ServerAgentStatus), color-coded on the frontend:
 * green / red / amber.
 */
export type AgentStatus = string;
/**
 * AgentStatusOK (green): the agent is reachable and answering — which for an
 * SSH-tunnelled server also means its tunnel is up.
 */
export const AgentStatusOK: AgentStatus = "ok";
/**
 * AgentStatusDown (red): the connection to the agent is down — the SSH
 * tunnel could not be brought up, or an mTLS agent (reached directly) is
 * unreachable.
 */
export const AgentStatusDown: AgentStatus = "down";
/**
 * AgentStatusDegraded (amber): the SSH tunnel is up but the agent behind it
 * isn't responding, or the state is otherwise indeterminate.
 */
export const AgentStatusDegraded: AgentStatus = "degraded";
/**
 * AgentTLS holds the mTLS material for direct (non-tunnelled) communication
 * with the agent on a public ("white") IP. CA is kept so awg-admin can
 * re-issue Server/Client certs later (e.g. on renewal) without invalidating
 * the other side. Server is deployed to the agent; Client is used by
 * awg-admin itself when dialing the agent directly.
 */
export interface AgentTLS {
  ca: CertKeyPair;
  server: CertKeyPair;
  client: CertKeyPair;
}
export interface CertKeyPair {
  cert: string;
  pk: string;
}
export interface Interface extends InterfaceConfig {
  id: string;
  /**
   * Sync status of this interface's config against the agent. Updated
   * after every push attempt (see internal/service's agent push wiring);
   * not touched by the agent itself.
   */
  inSync: boolean;
  lastSyncError?: string;
  lastSyncedAt?: number /* time.Time */;
  /**
   * Tunnel groups the interfaces that together form one multi-hop tunnel
   * (see Service.BuildTunnel / the tunnel wizard): every interface a tunnel
   * is built from carries the same id, nil means "not part of any tunnel".
   * Admin-only bookkeeping — never pushed to the agent (only the embedded
   * InterfaceConfig is), not shown or editable in the UI. Its only visible
   * effects: it blocks deleting the interface while the tunnel exists, and
   * the dashboard counts distinct tunnel ids.
   */
  tunnel?: string;
}

//////////
// source: tunnel.go

/**
 * TunnelStep identifies one interface a tunnel is built from, given in order
 * (entry first, exit last). Input to Service.BuildTunnel.
 */
export interface TunnelStep {
  serverId: string;
  ifaceId: string;
}
/**
 * TunnelMember is one interface belonging to a tunnel, for display in the
 * tunnel list. Role is derived from the interface's config ("entry" keeps its
 * listen port and relays; "exit" has none and NATs).
 */
export interface TunnelMember {
  serverId: string;
  serverName: string;
  ifaceId: string;
  interface: string;
  role: string;
}
/**
 * Tunnel is the derived view of the interfaces sharing one Tunnel id. It is
 * NOT persisted as its own entity — it's reconstructed from the Tunnel field
 * on models.Interface (see Service.ListTunnels).
 */
export interface Tunnel {
  id: string;
  members: TunnelMember[];
}

//////////
// source: user.go

export interface User {
  id: string;
  name: string;
  description?: string;
  disabled?: boolean;
  peers?: Peer[];
}
export interface Peer {
  name: string;
  pk: Key;
  interface: string;
  disabled?: boolean;
  /**
   * DNS is the client-side DNS for this peer's generated wg-quick config
   * (the `[Interface] DNS = …` line). Admin-only: it's never pushed to the
   * agent (DNS is a client setting). Empty falls back to the owning
   * interface's DNS in GetPeerConfig.
   */
  dns?: string[];
}
