// Code generated by tygo. DO NOT EDIT.
/*
  Copyright © 2026 Alexey Shulutkov <github@shulutkov.ru>

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  	http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */

//////////
// source: agent.go

export interface AgentInfo {
  mid: number /* uint64 */;
  devices: DeviceInfo[];
}

//////////
// source: metrics.go

/**
 * SystemSnapshot is the latest recorded host-level sample.
 */
export interface SystemSnapshot {
  timestamp: number /* time.Time */;
  cpuPercent: number /* float64 */;
  memUsedBytes: number /* uint64 */;
  memTotalBytes: number /* uint64 */;
  load1: number /* float64 */;
  load5: number /* float64 */;
  load15: number /* float64 */;
  /**
   * NetRxBytes/NetTxBytes are bytes transferred *during this one
   * collection interval* (e.g. the last 45s, see
   * AWG_AGENT_METRICS_INTERVAL), not the host's cumulative since-boot
   * counters from /proc/net/dev — those only ever climb and aren't
   * useful for "how much traffic is this server actually moving" (see
   * agent/internal/metrics/collector.go's collectSystem).
   */
  netRxBytes: number /* uint64 */;
  netTxBytes: number /* uint64 */;
}
/**
 * PeerSnapshot is the latest recorded sample for one peer of one interface.
 */
export interface PeerSnapshot {
  publicKey: string;
  rx: number /* uint64 */;
  tx: number /* uint64 */;
  lastHandshake: number /* time.Time */;
}
/**
 * InterfaceSnapshot groups peer snapshots under their interface name.
 */
export interface InterfaceSnapshot {
  interface: string;
  peers: PeerSnapshot[];
}
/**
 * MetricsSnapshot is the full GET /metrics response: the latest known
 * value of every metric the agent has collected.
 */
export interface MetricsSnapshot {
  system: SystemSnapshot;
  interfaces: InterfaceSnapshot[];
}
/**
 * SystemHistoryPoint is one retained host-level sample, aligned across
 * metrics by timestamp (see Collector.SystemHistory). Like SystemSnapshot,
 * NetRxBytes/NetTxBytes are per-interval deltas, not cumulative counters.
 */
export interface SystemHistoryPoint {
  timestamp: number /* time.Time */;
  cpuPercent: number /* float64 */;
  memUsedBytes: number /* uint64 */;
  memTotalBytes: number /* uint64 */;
  netRxBytes: number /* uint64 */;
  netTxBytes: number /* uint64 */;
}
/**
 * SystemHistory is the full GET /metrics/history response: every host-level
 * sample (Points) plus every per-peer sample (Interfaces) still retained in
 * the agent's in-memory ring buffers (up to 48h, oldest first — see
 * agent/internal/metrics's package doc comment), for rendering charts instead
 * of just the latest value. History is served only through this one endpoint;
 * the per-peer series ride along here rather than on a separate route. Points
 * stays the top-level field it always was, so existing consumers that only
 * read host history are unaffected.
 */
export interface SystemHistory {
  points: SystemHistoryPoint[];
  interfaces: InterfaceHistory[];
}
/**
 * PeerHistoryPoint is one retained sample for a single peer. Unlike
 * SystemHistoryPoint's per-interval network deltas, RxBytes/TxBytes are the
 * cumulative byte counters WireGuard reports for the peer (same as
 * PeerSnapshot); differencing consecutive points yields per-interval traffic.
 * LastHandshake is the peer's last successful handshake at that sample (zero
 * value if it had never completed one yet).
 */
export interface PeerHistoryPoint {
  timestamp: number /* time.Time */;
  rx: number /* uint64 */;
  tx: number /* uint64 */;
  lastHandshake: number /* time.Time */;
}
/**
 * PeerHistory is every retained sample for one peer, oldest first.
 */
export interface PeerHistory {
  publicKey: string;
  points: PeerHistoryPoint[];
}
/**
 * InterfaceHistory groups per-peer history under their interface name, as
 * carried in SystemHistory.Interfaces.
 */
export interface InterfaceHistory {
  interface: string;
  peers: PeerHistory[];
}

//////////
// source: wg.go

export type Key = string;
export interface InterfaceConfig {
  iface: string;
  /**
   * PrivateKey specifies a private key configuration, if not nil.
   */
  pk: Key;
  /**
   * ListenPort specifies a device's listening port, if not nil.
   */
  listen: number /* uint16 */;
  addr: string;
  mtu?: number /* int */;
  dns?: string[];
  disabled?: boolean;
  /**
   * Table the routing table number
   */
  table?: number /* int */;
  /**
   * FirewallMark specifies a device's firewall mark, if not nil.
   * If non-nil and set to 0, the firewall mark will be cleared.
   */
  fwMark?: number /* int */;
  preUp?: string[]; // action that is executed before the device is up
  postUp?: string[]; // action that is executed after the device is up
  preDown?: string[]; // action that is executed before the device is down
  postDown?: string[]; // action that is executed after the device is down
  /**
   * Peers specifies a list of peer configurations to apply to a device.
   */
  peers?: InterfacePeer[];
  /**
   * Junk Packet parameters
   */
  jc?: number /* int */; // Count
  jmin?: number /* int */; // Min size
  jmax?: number /* int */; // Max size
  /**
   * Message Padding parameters (bytes)
   */
  s1?: number /* int */; // Init
  s2?: number /* int */; // Response
  s3?: number /* int */; // Cookie
  s4?: number /* int */; // Transport
  /**
   * Message Magic Headers
   * In AmneziaWG 2.0 these should be ranges (e.g., "123456-123999")
   */
  h1?: string; // Init
  h2?: string; // Response
  h3?: string; // Cookie
  h4?: string; // Transport
  /**
   * Init Packet Magic / Custom Signature (obfuscation)
   * For client-side explicit setups only.
   */
  i1?: string;
  i2?: string;
  i3?: string;
  i4?: string;
  i5?: string;
}
export interface InterfacePeer {
  key: Key;
  psk?: Key;
  ips: string[];
  endpoint?: string;
  keepalive: number /* time in nanoseconds (time.Duration) */;
}
export interface DeviceInfo {
  name: string;
  publicKey: Key;
  type: any /* wgtypes.DeviceType */;
  listenPort: number /* int */;
  firewallMark: number /* int */;
  isAmnezia: boolean;
  peers: PeerInfo[];
}
export interface PeerInfo {
  publicKey: Key;
  endpoint: string;
  lastHandshake: number /* time.Time */;
  rx: number /* int64 */;
  tx: number /* int64 */;
  online: boolean;
  updated_at: number /* time.Time */;
}
