// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1, arg2) {
  return window['go']['main']['App']['AddPeer'](arg1, arg2);
}

export function Backup() {
  return window['go']['main']['App']['Backup']();
}

export function BasicAuthEnabled() {
  return window['go']['main']['App']['BasicAuthEnabled']();
}

export function BuildTunnel(arg1, arg2) {
  return window['go']['main']['App']['BuildTunnel'](arg1, arg2);
}

export function ChangeCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeCredentials'](arg1, arg2, arg3);
}

export function CreateAgentSource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAgentSource'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateInterface(arg1, arg2) {
  return window['go']['main']['App']['CreateInterface'](arg1, arg2);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function CurrentUsername() {
  return window['go']['main']['App']['CurrentUsername']();
}

export function DebugLoggingEnabled() {
  return window['go']['main']['App']['DebugLoggingEnabled']();
}

export function DeleteAgentInterface(arg1, arg2) {
  return window['go']['main']['App']['DeleteAgentInterface'](arg1, arg2);
}

export function DeleteAgentSource(arg1) {
  return window['go']['main']['App']['DeleteAgentSource'](arg1);
}

export function DeleteInterface(arg1, arg2) {
  return window['go']['main']['App']['DeleteInterface'](arg1, arg2);
}

export function DeletePeer(arg1, arg2) {
  return window['go']['main']['App']['DeletePeer'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeployAgent(arg1, arg2) {
  return window['go']['main']['App']['DeployAgent'](arg1, arg2);
}

export function GenerateAgentTLS(arg1) {
  return window['go']['main']['App']['GenerateAgentTLS'](arg1);
}

export function GenerateInterfaceDefaults() {
  return window['go']['main']['App']['GenerateInterfaceDefaults']();
}

export function GetDeployStatus(arg1) {
  return window['go']['main']['App']['GetDeployStatus'](arg1);
}

export function GetInterface(arg1, arg2) {
  return window['go']['main']['App']['GetInterface'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPeer(arg1, arg2) {
  return window['go']['main']['App']['GetPeer'](arg1, arg2);
}

export function GetPeerConfig(arg1, arg2) {
  return window['go']['main']['App']['GetPeerConfig'](arg1, arg2);
}

export function GetPeerQRCode(arg1, arg2) {
  return window['go']['main']['App']['GetPeerQRCode'](arg1, arg2);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServerMetrics(arg1) {
  return window['go']['main']['App']['GetServerMetrics'](arg1);
}

export function GetServerMetricsHistory(arg1) {
  return window['go']['main']['App']['GetServerMetricsHistory'](arg1);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function ImportInterface(arg1, arg2) {
  return window['go']['main']['App']['ImportInterface'](arg1, arg2);
}

export function ListAgentSources() {
  return window['go']['main']['App']['ListAgentSources']();
}

export function ListInterfaces(arg1) {
  return window['go']['main']['App']['ListInterfaces'](arg1);
}

export function ListPeers(arg1) {
  return window['go']['main']['App']['ListPeers'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MigratePeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['MigratePeer'](arg1, arg2, arg3);
}

export function ReconcileServer(arg1) {
  return window['go']['main']['App']['ReconcileServer'](arg1);
}

export function RefreshAgentSourceCache(arg1) {
  return window['go']['main']['App']['RefreshAgentSourceCache'](arg1);
}

export function RemoveTunnel(arg1) {
  return window['go']['main']['App']['RemoveTunnel'](arg1);
}

export function SaveBackup() {
  return window['go']['main']['App']['SaveBackup']();
}

export function SaveLogs() {
  return window['go']['main']['App']['SaveLogs']();
}

export function SavePeerQRCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePeerQRCode'](arg1, arg2, arg3);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function ServerAgentStatus(arg1) {
  return window['go']['main']['App']['ServerAgentStatus'](arg1);
}

export function ServerHostInfo(arg1) {
  return window['go']['main']['App']['ServerHostInfo'](arg1);
}

export function SetBasicAuthEnabled(arg1) {
  return window['go']['main']['App']['SetBasicAuthEnabled'](arg1);
}

export function SetDebugLogging(arg1) {
  return window['go']['main']['App']['SetDebugLogging'](arg1);
}

export function SetPeerDisabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPeerDisabled'](arg1, arg2, arg3);
}

export function SetServerMonitoring(arg1, arg2) {
  return window['go']['main']['App']['SetServerMonitoring'](arg1, arg2);
}

export function StartTunnels() {
  return window['go']['main']['App']['StartTunnels']();
}

export function StopTunnels() {
  return window['go']['main']['App']['StopTunnels']();
}

export function SyncServer(arg1) {
  return window['go']['main']['App']['SyncServer'](arg1);
}

export function UnlockServerSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnlockServerSSH'](arg1, arg2, arg3);
}

export function UpdateInterfaceConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateInterfaceConfig'](arg1, arg2, arg3);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function VerifyBasicAuth(arg1, arg2) {
  return window['go']['main']['App']['VerifyBasicAuth'](arg1, arg2);
}
