// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {models} from '../models';

export function AddPeer(arg1:string,arg2:service.AddPeerInput):Promise<models.User>;

export function Backup():Promise<Array<number>>;

export function BasicAuthEnabled():Promise<boolean>;

export function BuildTunnel(arg1:Array<models.TunnelStep>,arg2:string):Promise<models.Tunnel>;

export function ChangeCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateAgentSource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<models.AgentSource>;

export function CreateInterface(arg1:string,arg2:models.InterfaceConfig):Promise<models.Interface>;

export function CreateServer(arg1:service.ServerInput):Promise<models.Server>;

export function CreateUser(arg1:service.UserInput):Promise<models.User>;

export function CurrentUsername():Promise<string>;

export function DebugLoggingEnabled():Promise<boolean>;

export function DeleteAgentInterface(arg1:string,arg2:string):Promise<void>;

export function DeleteAgentSource(arg1:string):Promise<void>;

export function DeleteInterface(arg1:string,arg2:string):Promise<void>;

export function DeletePeer(arg1:string,arg2:string):Promise<models.User>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DeployAgent(arg1:string,arg2:string):Promise<void>;

export function GenerateAgentTLS(arg1:string):Promise<models.Server>;

export function GenerateInterfaceDefaults():Promise<models.InterfaceConfig>;

export function GetDeployStatus(arg1:string):Promise<models.DeployStatus>;

export function GetInterface(arg1:string,arg2:string):Promise<models.Interface>;

export function GetLogs():Promise<string>;

export function GetPeer(arg1:string,arg2:string):Promise<models.Peer>;

export function GetPeerConfig(arg1:string,arg2:string):Promise<string>;

export function GetPeerQRCode(arg1:string,arg2:string):Promise<string>;

export function GetServer(arg1:string):Promise<models.Server>;

export function GetServerMetrics(arg1:string):Promise<models.MetricsSnapshot>;

export function GetServerMetricsHistory(arg1:string):Promise<models.SystemHistory>;

export function GetServerProfile(arg1:string,arg2:string,arg3:number):Promise<service.ProfileDump>;

export function GetUser(arg1:string):Promise<models.User>;

export function ImportInterface(arg1:string,arg2:string):Promise<models.Interface>;

export function ListAgentSources():Promise<Array<models.AgentSource>>;

export function ListInterfaces(arg1:string):Promise<Array<models.Interface>>;

export function ListPeers(arg1:string):Promise<Array<models.Peer>>;

export function ListServers():Promise<Array<models.Server>>;

export function ListTunnels():Promise<Array<models.Tunnel>>;

export function ListUsers():Promise<Array<models.User>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function MigratePeer(arg1:string,arg2:string,arg3:string):Promise<models.User>;

export function ReconcileServer(arg1:string):Promise<service.ReconcileReport>;

export function RefreshAgentSourceCache(arg1:string):Promise<void>;

export function RemoveTunnel(arg1:string):Promise<void>;

export function SaveBackup():Promise<boolean>;

export function SaveLogs():Promise<boolean>;

export function SavePeerQRCode(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveServerProfile(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function SelectFile(arg1:string):Promise<string>;

export function ServerAgentStatus(arg1:string):Promise<models.AgentStatus>;

export function ServerHostInfo(arg1:string):Promise<models.HostInfo>;

export function SetBasicAuthEnabled(arg1:boolean):Promise<void>;

export function SetDebugLogging(arg1:boolean):Promise<void>;

export function SetPeerDisabled(arg1:string,arg2:string,arg3:boolean):Promise<models.User>;

export function SetServerMonitoring(arg1:string,arg2:boolean):Promise<models.Server>;

export function SetServerProfiling(arg1:string,arg2:boolean):Promise<models.Server>;

export function StartTunnels():Promise<void>;

export function StopTunnels():Promise<void>;

export function SyncServer(arg1:string):Promise<void>;

export function UnlockServerSSH(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateInterfaceConfig(arg1:string,arg2:string,arg3:models.InterfaceConfig):Promise<models.Interface>;

export function UpdateServer(arg1:string,arg2:service.ServerInput):Promise<models.Server>;

export function UpdateUser(arg1:string,arg2:service.UserInput):Promise<models.User>;

export function VerifyBasicAuth(arg1:string,arg2:string):Promise<boolean>;
